stages:
  - build
  - publish
  - cleanup

build:
  stage: build
  tags:
    - shell-runner
  script:
    - docker build . --squash -t andrewmontagne/larp-stack:$CI_COMMIT_SHORT_SHA

docker-hub:
  stage: publish
  tags:
    - shell-runner
  script:
    - docker push andrewmontagne/larp-stack:$CI_COMMIT_SHORT_SHA
    - docker tag andrewmontagne/larp-stack:$CI_COMMIT_SHORT_SHA andrewmontagne/larp-stack:$CI_COMMIT_BRANCH
    - docker push andrewmontagne/larp-stack:$CI_COMMIT_BRANCH

prune:
  stage: cleanup
  tags:
    - shell-runner
  script:
    - docker rmi andrewmontagne/larp-stack:$CI_COMMIT_SHORT_SHA

downstream:
  stage: cleanup
  trigger: docker-containers/larp-dev